server:
  port: 8080

ani:
  jwt:
    location: classpath:anihub.jks
    alias: anihub
    password: bianxin123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /users/test
      - /items/**
      - /hi