server:
  port: 8082
ani:
  swagger:
    title: 用户服务接口文档
    package: com.anihub.user.controller
  db:
    database: ani-user
  jwt:
    location: classpath:anihub.jks
    alias: anihub
    password: bianxin123
    tokenTTL: 240m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /users/test
      - /items/**
      - /hi